// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL="https://mfierzkpebmkznjahdsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1maWVyemtwZWJta3puamFoZHNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NzAzODMsImV4cCI6MjA2MTU0NjM4M30.lJJGkDFj_4KDjltGxj33g05h6QCweslfLVPyHPQsmvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);